markdown: kramdown
highlighter: rouge

title: HydeoutW
tagline: 'A Jekyll theme'
description: 'The Hyde theme for Jekyll, refreshed.'
url: https://wklteam64.github.io
baseurl: '' # <-- set to '' for root

author:
  name: 'WKL team64'
  url: www.wklteam64.pl

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link: true

show_excerpts: true
show_frame: true
show_sidebar: true
show_minimal: false

navigation:
  - {file: "index.html", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}