markdown: kramdown
highlighter: rouge

title: WKL TEAM64 
tagline: 'Strona www instrukcji i tutoriali'
description: 'statyczna strona www instrukcji i tutoriali'
url: https://wklteam64.github.io
baseurl: '' # <-- set to '' for root

author:
  name: 'WKL team64'
  url: www.wklteam64.pl

paginate: 5

sidebar_home_link: true

show_excerpts: true
show_frame: true
show_sidebar: true
show_minimal: false

navigation:
  - {file: "index.html", title: "Strona główna", sidebaricon: home}
  - {file: "README.md", title: "O nas",  sidebaricon: address-card}
  #- {file: "kontakt.md", title: "Kontakt", sidebaricon: envelope}


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
