markdown: kramdown
highlighter: rouge

title: WKL TEAM64 
tagline: 'Strona www instrukcji i tutoriali'
description: 'WKL TEAM64 manuals'
url: https://wklteam64.github.io
baseurl: '' # <-- set to '' for root

author:
  name: 'WKL team64'
  url: www.wklteam64.pl

paginate: 5

sidebar_home_link: true

show_excerpts: true
show_frame: true
show_sidebar: true
show_minimal: false

navigation:
  - {file: "index.md", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}

  
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
